version: "3.7"
services:
  share_nodejs:
    container_name: share_nodejs
    build: .
    ports:
      - "3000:3000"
    networks:
      - share_network
  share_db:
    image: mysql:5.7
    container_name: share_db
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=to_do_list
    networks:
      - share_network
networks:
  share_network:
    driver: bridge
